// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvzOHlhLnUpDxQKQPqj4H_cpmECpNiEO4',
    appId: '1:1088534743968:web:6933bcab8c61fc8bd7f2c5',
    messagingSenderId: '1088534743968',
    projectId: 'tfg-carecoins',
    authDomain: 'tfg-carecoins.firebaseapp.com',
    storageBucket: 'tfg-carecoins.firebasestorage.app',
    measurementId: 'G-FE0YM7LRQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDe1lyStEZtgWx70kiy7yoePmiMvtCyVQ',
    appId: '1:1088534743968:android:efa4954af2f43fe2d7f2c5',
    messagingSenderId: '1088534743968',
    projectId: 'tfg-carecoins',
    storageBucket: 'tfg-carecoins.firebasestorage.app',
  );

  // Hand-written from ios/Runner/GoogleService-Info.plist because
  // `flutterfire configure --platforms=ios` needs the xcodeproj gem;
  // the values are identical to what the CLI would generate.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATjRy1vJZIpiuky37m3UM-BSKrpBuwOn0',
    appId: '1:1088534743968:ios:643a6a4871ffe3c7d7f2c5',
    messagingSenderId: '1088534743968',
    projectId: 'tfg-carecoins',
    storageBucket: 'tfg-carecoins.firebasestorage.app',
    iosClientId:
        '1088534743968-kldnrth77ts11q77o2r0pt4d7ems39c7.apps.googleusercontent.com',
    iosBundleId: 'com.carecoins.carecoinsFlutter',
  );
}
